### ISSUE TITLE
Repository link broken in extension's 'DETAILS' page in VSCode

### ISSUE THREAD

**Issue by sjsepan3** [teguhsaint/iconsgallery#1]
In the Details tab of the extension's descriptive page in VSCode, the Repository link goes to 
[https://github.com/iconsgallery.git](https://github.com/iconsgallery.git)
which results in a page with a 'Not Found' error in the browser.

After some searching, I located this repository at
[https://github.com/teguhsaint/iconsgallery](https://github.com/teguhsaint/iconsgallery)

PS -- love the extension, very helpful!

**Comment by teguhsaint** [comment]
I'll Fix this Soon

**Comment by sjsepan3** [comment]
Yes, looks good now, Thanks!
