### ISSUE TITLE
Search text not re-applied when changing icon collection

### ISSUE THREAD

**Issue by sjsepan3** [teguhsaint/iconsgallery#2]
If I enter search text while a given collection is selected, I see the result narrowed as expected. But if I then change the selected collection, the search text is not applied, and the full collection is displayed in the results. I must then _modify_ the search text in order to have it affect the results;. just clicking Enter in the search field will not do it.

**Comment by teguhsaint** [comment]
Ok I'll Fixed Soon

**Comment by sjsepan3** [comment]
Yes, this too looks good now; Thank You!
